// FILE GENERATED WITH SCRIPT
/** @type {import('eslint').Linter.FlatConfig} */
export default {
	languageOptions: {
		ecmaVersion: 2022,
		sourceType: 'module',
		parserOptions: { ecmaVersion: 2022, sourceType: 'module', project: true },
	},
	settings: {
		'import/resolver': {
			node: { extensions: ['.json'] },
			typescript: { extensions: ['.js', '.mjs', '.ts', '.mts'] },
		},
		'import/extensions': ['.js', '.mjs', '.jsx'],
		'import/core-modules': [],
		'import/ignore': [
			'node_modules',
			'\\.(coffee|scss|css|less|hbs|svg|json)$',
		],
		'import/extenstions': ['.js', '.mjs', '.ts', '.mts'],
		'import/parsers': { '@typescript-eslint/parser': ['.ts', '.mts'] },
	},
	rules: {
		'block-spacing': 0,
		'brace-style': 0,
		'class-methods-use-this': 0,
		'comma-dangle': 0,
		'comma-spacing': 0,
		'default-param-last': 0,
		'dot-notation': 0,
		'func-call-spacing': 0,
		indent: 0,
		'init-declarations': 0,
		'key-spacing': 0,
		'keyword-spacing': 0,
		'lines-around-comment': 0,
		'lines-between-class-members': 0,
		'max-params': 0,
		'no-array-constructor': 0,
		'no-dupe-class-members': 0,
		'no-empty-function': 0,
		'no-extra-parens': 0,
		'no-extra-semi': 0,
		'no-implied-eval': 0,
		'no-invalid-this': 0,
		'no-loop-func': 0,
		'no-loss-of-precision': 0,
		'no-magic-numbers': 0,
		'no-redeclare': 0,
		'no-restricted-imports': 0,
		'no-shadow': 0,
		'no-throw-literal': 0,
		'no-unused-expressions': 0,
		'no-unused-vars': 0,
		'no-use-before-define': 0,
		'no-useless-constructor': 0,
		'object-curly-spacing': 0,
		'padding-line-between-statements': 0,
		'prefer-destructuring': 0,
		quotes: 0,
		'require-await': 0,
		semi: 0,
		'space-before-blocks': 0,
		'space-before-function-paren': 0,
		'space-infix-ops': 0,
		'import/extensions': [
			'error',
			'ignorePackages',
			{
				js: 'never', mjs: 'never', jsx: 'never', ts: 'never', tsx: 'never',
			},
		],
		'import/no-extraneous-dependencies': [
			'error',
			{
				devDependencies: [
					'test/**',
					'tests/**',
					'spec/**',
					'**/__tests__/**',
					'**/__mocks__/**',
					'test.{js,jsx}',
					'test-*.{js,jsx}',
					'**/*{.,_}{test,spec}.{js,jsx}',
					'**/jest.config.js',
					'**/jest.setup.js',
					'**/vue.config.js',
					'**/webpack.config.js',
					'**/webpack.config.*.js',
					'**/rollup.config.js',
					'**/rollup.config.*.js',
					'**/gulpfile.js',
					'**/gulpfile.*.js',
					'**/Gruntfile{,.js}',
					'**/protractor.conf.js',
					'**/protractor.conf.*.js',
					'**/karma.conf.js',
					'**/.eslintrc.js',
					'**/eslint.config.js',
					'**/vite.config.js',
					'**/vite.config.*.js',
					'test.{ts,tsx}',
					'test-*.{ts,tsx}',
					'**/*{.,_}{test,spec}.{ts,tsx}',
					'**/jest.config.ts',
					'**/jest.setup.ts',
					'**/vue.config.ts',
					'**/webpack.config.ts',
					'**/webpack.config.*.ts',
					'**/rollup.config.ts',
					'**/rollup.config.*.ts',
					'**/gulpfile.ts',
					'**/gulpfile.*.ts',
					'**/Gruntfile{,.ts}',
					'**/protractor.conf.ts',
					'**/protractor.conf.*.ts',
					'**/karma.conf.ts',
					'**/eslint.config.ts',
					'**/vite.config.ts',
					'**/vite.config.*.ts',
				],
				optionalDependencies: false,
			},
		],
		'import/named': 0,
		'import/no-named-as-default-member': 0,
		'typescript/block-spacing': 0,
		'typescript/brace-style': 0,
		'typescript/class-methods-use-this': ['error', { exceptMethods: [] }],
		'typescript/comma-dangle': 0,
		'typescript/comma-spacing': 0,
		'typescript/default-param-last': 'error',
		'typescript/dot-notation': ['error', { allowKeywords: true }],
		'typescript/func-call-spacing': 0,
		'typescript/indent': 0,
		'typescript/init-declarations': 'off',
		'typescript/key-spacing': 0,
		'typescript/keyword-spacing': 0,
		'typescript/lines-around-comment': 0,
		'typescript/lines-between-class-members': 0,
		'typescript/max-params': ['off', 3],
		'typescript/no-array-constructor': 'error',
		'typescript/no-dupe-class-members': 'error',
		'typescript/no-empty-function': [
			'error',
			{ allow: ['arrowFunctions', 'functions', 'methods'] },
		],
		'typescript/no-extra-parens': 0,
		'typescript/no-extra-semi': 0,
		'typescript/no-implied-eval': 'error',
		'typescript/no-invalid-this': 'off',
		'typescript/no-loop-func': 'error',
		'typescript/no-loss-of-precision': 'error',
		'typescript/no-magic-numbers': [
			'off',
			{
				ignore: [],
				ignoreArrayIndexes: true,
				enforceConst: true,
				detectObjects: false,
			},
		],
		'typescript/no-redeclare': 'error',
		'typescript/no-restricted-imports': ['off', { paths: [], patterns: [] }],
		'typescript/no-shadow': 'error',
		'typescript/no-throw-literal': 'error',
		'typescript/no-unused-expressions': [
			'error',
			{
				allowShortCircuit: false,
				allowTernary: false,
				allowTaggedTemplates: false,
			},
		],
		'typescript/no-unused-vars': [
			'error',
			{ vars: 'all', args: 'after-used', ignoreRestSiblings: true },
		],
		'typescript/no-use-before-define': [
			'error',
			{ functions: true, classes: true, variables: true },
		],
		'typescript/no-useless-constructor': 'error',
		'typescript/object-curly-spacing': 0,
		'typescript/padding-line-between-statements': 0,
		'typescript/prefer-destructuring': [
			'error',
			{
				VariableDeclarator: { array: false, object: true },
				AssignmentExpression: { array: true, object: false },
			},
			{ enforceForRenamedProperties: false },
		],
		'typescript/quotes': 0,
		'typescript/require-await': 'off',
		'typescript/semi': 0,
		'typescript/space-before-blocks': 0,
		'typescript/space-before-function-paren': 0,
		'typescript/space-infix-ops': 0,
	},
};
