// FILE GENERATED WITH SCRIPT
/** @type {import('../../../shared/types.d.ts').NamedFlatConfig} */
export default {
	name: 'airbnb:disable-legacy',
	rules: {
		'callback-return': 0,
		'global-require': 0,
		'handle-callback-err': 0,
		'import/imports-first': 0,
		'lines-around-directive': 0,
		'newline-after-var': 0,
		'newline-before-return': 0,
		'no-buffer-constructor': 0,
		'no-catch-shadow': 0,
		'no-mixed-requires': 0,
		'no-native-reassign': 0,
		'no-negated-in-lhs': 0,
		'no-new-object': 0,
		'no-new-require': 0,
		'no-path-concat': 0,
		'no-process-env': 0,
		'no-process-exit': 0,
		'no-restricted-modules': 0,
		'no-return-await': 0,
		'no-spaced-func': 0,
		'no-sync': 0,
		'prefer-reflect': 0,
		'require-jsdoc': 0,
		'valid-jsdoc': 0,
	},
};
