// FILE GENERATED WITH SCRIPT

import type { Linter } from 'eslint';

export default {
	name: 'airbnb:typescript',
	languageOptions: {
		ecmaVersion: 2022,
		sourceType: 'module',
		parserOptions: {
			ecmaVersion: 2022,
			sourceType: 'module',
			project: true,
		},
	},
	settings: {
		'import/resolver': {
			node: { extensions: ['.json'] },
			typescript: {
				extensions: [
					'.js',
					'.mjs',
					'.ts',
					'.mts',
				],
			},
		},
		'import/extensions': [
			'.js',
			'.mjs',
			'.ts',
			'.mts',
		],
		'import/core-modules': [],
		'import/ignore': ['node_modules', '\\.(coffee|scss|css|less|hbs|svg|json)$'],
		'import/external-module-folders': ['node_modules', 'node_modules/@types'],
		'import/parsers': {
			'@typescript-eslint/parser': [
				'.js',
				'.mjs',
				'.ts',
				'.mts',
			],
		},
	},
	rules: {
		'class-methods-use-this': 0,
		'consistent-return': 0,
		'default-param-last': 0,
		'dot-notation': 0,
		'import/no-namespace': 0,
		'init-declarations': 0,
		'max-params': 0,
		'no-array-constructor': 0,
		'no-dupe-class-members': 0,
		'no-empty-function': 0,
		'no-implied-eval': 0,
		'no-invalid-this': 0,
		'no-loop-func': 0,
		'no-loss-of-precision': 0,
		'no-magic-numbers': 0,
		'no-redeclare': 0,
		'no-restricted-imports': 0,
		'no-shadow': 0,
		'no-unused-expressions': 0,
		'no-unused-vars': 0,
		'no-use-before-define': 0,
		'no-useless-constructor': 0,
		'prefer-destructuring': 0,
		'prefer-promise-reject-errors': 0,
		'require-await': 0,
		'type/block-spacing': 0,
		'type/brace-style': 0,
		'type/class-methods-use-this': ['error', { exceptMethods: [] }],
		'type/comma-dangle': 0,
		'type/comma-spacing': 0,
		'type/consistent-return': 'error',
		'type/default-param-last': 'error',
		'type/dot-notation': ['error', { allowKeywords: true }],
		'type/func-call-spacing': 0,
		'type/indent': 0,
		'type/init-declarations': 'off',
		'type/key-spacing': 0,
		'type/keyword-spacing': 0,
		'type/lines-around-comment': 0,
		'type/lines-between-class-members': 0,
		'type/max-params': ['off', 3],
		'type/no-array-constructor': 'error',
		'type/no-dupe-class-members': 'error',
		'type/no-empty-function': [
			'error',
			{
				allow: [
					'arrowFunctions',
					'functions',
					'methods',
				],
			},
		],
		'type/no-extra-parens': 0,
		'type/no-extra-semi': 0,
		'type/no-implied-eval': 'error',
		'type/no-invalid-this': 'off',
		'type/no-loop-func': 'error',
		'type/no-loss-of-precision': 'error',
		'type/no-magic-numbers': [
			'off',
			{
				ignore: [],
				ignoreArrayIndexes: true,
				enforceConst: true,
				detectObjects: false,
			},
		],
		'type/no-namespace': 'off',
		'type/no-redeclare': 'error',
		'type/no-restricted-imports': [
			'off',
			{
				paths: [],
				patterns: [],
			},
		],
		'type/no-shadow': 'error',
		'type/no-throw-literal': 0,
		'type/no-unused-expressions': [
			'error',
			{
				allowShortCircuit: false,
				allowTernary: false,
				allowTaggedTemplates: false,
			},
		],
		'type/no-unused-vars': [
			'error',
			{
				vars: 'all',
				args: 'after-used',
				ignoreRestSiblings: true,
			},
		],
		'type/no-use-before-define': [
			'error',
			{
				functions: true,
				classes: true,
				variables: true,
			},
		],
		'type/no-useless-constructor': 'error',
		'type/object-curly-spacing': 0,
		'type/padding-line-between-statements': 0,
		'type/prefer-destructuring': [
			'error',
			{
				VariableDeclarator: {
					array: false,
					object: true,
				},
				AssignmentExpression: {
					array: true,
					object: false,
				},
			},
			{ enforceForRenamedProperties: false },
		],
		'type/prefer-promise-reject-errors': ['error', { allowEmptyReject: true }],
		'type/quotes': 0,
		'type/require-await': 'off',
		'type/semi': 0,
		'type/space-before-blocks': 0,
		'type/space-before-function-paren': 0,
		'type/space-infix-ops': 0,
	},
} as Linter.FlatConfig;
