// FILE GENERATED WITH SCRIPT
/** @type {import('eslint').Linter.FlatConfig} */
export default {
	name: 'airbnb:typescript',
	rules: {
		'class-methods-use-this': 0,
		'typescript/class-methods-use-this': ['error', { exceptMethods: [] }],
		'default-param-last': 0,
		'typescript/default-param-last': 'error',
		'dot-notation': 0,
		'typescript/dot-notation': ['error', { allowKeywords: true }],
		'init-declarations': 0,
		'typescript/init-declarations': 'off',
		'max-params': 0,
		'typescript/max-params': ['off', 3],
		'no-array-constructor': 0,
		'typescript/no-array-constructor': 'error',
		'no-dupe-class-members': 0,
		'typescript/no-dupe-class-members': 'error',
		'no-empty-function': 0,
		'typescript/no-empty-function': [
			'error',
			{ allow: ['arrowFunctions', 'functions', 'methods'] },
		],
		'no-implied-eval': 0,
		'typescript/no-implied-eval': 'error',
		'no-invalid-this': 0,
		'typescript/no-invalid-this': 'off',
		'no-loop-func': 0,
		'typescript/no-loop-func': 'error',
		'no-loss-of-precision': 0,
		'typescript/no-loss-of-precision': 'error',
		'no-magic-numbers': 0,
		'typescript/no-magic-numbers': [
			'off',
			{
				ignore: [],
				ignoreArrayIndexes: true,
				enforceConst: true,
				detectObjects: false,
			},
		],
		'no-redeclare': 0,
		'typescript/no-redeclare': 'error',
		'no-restricted-imports': 0,
		'typescript/no-restricted-imports': ['off', { paths: [], patterns: [] }],
		'no-shadow': 0,
		'typescript/no-shadow': 'error',
		'no-throw-literal': 0,
		'typescript/no-throw-literal': 'error',
		'no-unused-expressions': 0,
		'typescript/no-unused-expressions': [
			'error',
			{
				allowShortCircuit: false,
				allowTernary: false,
				allowTaggedTemplates: false,
			},
		],
		'no-unused-vars': 0,
		'typescript/no-unused-vars': [
			'error',
			{ vars: 'all', args: 'after-used', ignoreRestSiblings: true },
		],
		'no-use-before-define': 0,
		'typescript/no-use-before-define': [
			'error',
			{ functions: true, classes: true, variables: true },
		],
		'no-useless-constructor': 0,
		'typescript/no-useless-constructor': 'error',
		'prefer-destructuring': 0,
		'typescript/prefer-destructuring': [
			'error',
			{
				VariableDeclarator: { array: false, object: true },
				AssignmentExpression: { array: true, object: false },
			},
			{ enforceForRenamedProperties: false },
		],
		'require-await': 0,
		'typescript/require-await': 'off',
	},
};
