// FILE GENERATED WITH SCRIPT
/** @type {import('eslint').Linter.FlatConfig} */
export default {
	name: 'airbnb:disable-legacy',
	rules: {
		'callback-return': 'off',
		'global-require': 'off',
		'handle-callback-err': 'off',
		'import/imports-first': 'off',
		'lines-around-directive': 'off',
		'newline-after-var': 'off',
		'newline-before-return': 'off',
		'no-buffer-constructor': 'off',
		'no-catch-shadow': 'off',
		'no-mixed-requires': 'off',
		'no-native-reassign': 'off',
		'no-negated-in-lhs': 'off',
		'no-new-object': 'off',
		'no-new-require': 'off',
		'no-path-concat': 'off',
		'no-process-env': 'off',
		'no-process-exit': 'off',
		'no-restricted-modules': 'off',
		'no-return-await': 'off',
		'no-spaced-func': 'off',
		'no-sync': 'off',
		'prefer-reflect': 'off',
		'require-jsdoc': 'off',
		'valid-jsdoc': 'off',
	},
};
