/** @file GENERATED WITH SCRIPT */
import type { FlatConfig } from '../../../src/globalTypes.ts';

export default {
	name: 'airbnb:es2022',
	languageOptions: {
		ecmaVersion: 2022,
		sourceType: 'module',
		parserOptions: {
			ecmaFeatures: {
				jsx: false,
				generators: false,
				objectLiteralDuplicateProperties: false,
			},
		},
		globals: {
			AggregateError: false,
			Array: false,
			ArrayBuffer: false,
			Atomics: false,
			BigInt: false,
			BigInt64Array: false,
			BigUint64Array: false,
			Boolean: false,
			DataView: false,
			Date: false,
			decodeURI: false,
			decodeURIComponent: false,
			encodeURI: false,
			encodeURIComponent: false,
			Error: false,
			escape: false,
			eval: false,
			EvalError: false,
			FinalizationRegistry: false,
			Float32Array: false,
			Float64Array: false,
			Function: false,
			globalThis: false,
			Infinity: false,
			Int16Array: false,
			Int32Array: false,
			Int8Array: false,
			Intl: false,
			isFinite: false,
			isNaN: false,
			JSON: false,
			Map: false,
			Math: false,
			NaN: false,
			Number: false,
			Object: false,
			parseFloat: false,
			parseInt: false,
			Promise: false,
			Proxy: false,
			RangeError: false,
			ReferenceError: false,
			Reflect: false,
			RegExp: false,
			Set: false,
			SharedArrayBuffer: false,
			String: false,
			Symbol: false,
			SyntaxError: false,
			TypeError: false,
			Uint16Array: false,
			Uint32Array: false,
			Uint8Array: false,
			Uint8ClampedArray: false,
			undefined: false,
			unescape: false,
			URIError: false,
			WeakMap: false,
			WeakRef: false,
			WeakSet: false,
		},
	},
	rules: {
		'arrow-body-style': [
			'error',
			'as-needed',
			{
				requireReturnForObjectLiteral: false,
			},
		],
		'constructor-super': 'error',
		'no-class-assign': 'error',
		'no-const-assign': 'error',
		'no-dupe-class-members': 'error',
		'no-duplicate-imports': 'off',
		'no-restricted-exports': [
			'error',
			{
				restrictedNamedExports: ['default', 'then'],
			},
		],
		'no-restricted-imports': [
			'off',
			{
				paths: [],
				patterns: [],
			},
		],
		'no-this-before-super': 'error',
		'no-useless-computed-key': 'error',
		'no-useless-constructor': 'error',
		'no-useless-rename': [
			'error',
			{
				ignoreDestructuring: false,
				ignoreImport: false,
				ignoreExport: false,
			},
		],
		'no-var': 'error',
		'object-shorthand': [
			'error',
			'always',
			{
				ignoreConstructors: false,
				avoidQuotes: true,
			},
		],
		'prefer-arrow-callback': [
			'error',
			{
				allowNamedFunctions: false,
				allowUnboundThis: true,
			},
		],
		'prefer-const': [
			'error',
			{
				destructuring: 'any',
				ignoreReadBeforeAssign: true,
			},
		],
		'prefer-destructuring': [
			'error',
			{
				VariableDeclarator: {
					array: false,
					object: true,
				},
				AssignmentExpression: {
					array: true,
					object: false,
				},
			},
			{
				enforceForRenamedProperties: false,
			},
		],
		'prefer-numeric-literals': 'error',
		'prefer-rest-params': 'error',
		'prefer-spread': 'error',
		'prefer-template': 'error',
		'require-yield': 'error',
		'sort-imports': [
			'off',
			{
				ignoreCase: false,
				ignoreDeclarationSort: false,
				ignoreMemberSort: false,
				memberSyntaxSortOrder: [
					'none',
					'all',
					'multiple',
					'single',
				],
			},
		],
		'symbol-description': 'error',
	},
} satisfies FlatConfig;
