// Rules generated with script
/** @type {import('eslint').Linter.FlatConfig} */
export default {
	name: 'airbnb:node',
	languageOptions: {
		globals: {
			__dirname: false,
			__filename: false,
			AbortController: false,
			AbortSignal: false,
			atob: false,
			Blob: false,
			BroadcastChannel: false,
			btoa: false,
			Buffer: false,
			ByteLengthQueuingStrategy: false,
			clearImmediate: false,
			clearInterval: false,
			clearTimeout: false,
			CompressionStream: false,
			console: false,
			CountQueuingStrategy: false,
			crypto: false,
			Crypto: false,
			CryptoKey: false,
			CustomEvent: false,
			DecompressionStream: false,
			DOMException: false,
			Event: false,
			EventTarget: false,
			exports: true,
			fetch: false,
			File: false,
			FormData: false,
			global: false,
			Headers: false,
			Intl: false,
			MessageChannel: false,
			MessageEvent: false,
			MessagePort: false,
			module: false,
			performance: false,
			PerformanceEntry: false,
			PerformanceMark: false,
			PerformanceMeasure: false,
			PerformanceObserver: false,
			PerformanceObserverEntryList: false,
			PerformanceResourceTiming: false,
			process: false,
			queueMicrotask: false,
			ReadableByteStreamController: false,
			ReadableStream: false,
			ReadableStreamBYOBReader: false,
			ReadableStreamBYOBRequest: false,
			ReadableStreamDefaultController: false,
			ReadableStreamDefaultReader: false,
			Request: false,
			require: false,
			Response: false,
			setImmediate: false,
			setInterval: false,
			setTimeout: false,
			structuredClone: false,
			SubtleCrypto: false,
			TextDecoder: false,
			TextDecoderStream: false,
			TextEncoder: false,
			TextEncoderStream: false,
			TransformStream: false,
			TransformStreamDefaultController: false,
			URL: false,
			URLSearchParams: false,
			WebAssembly: false,
			WritableStream: false,
			WritableStreamDefaultController: false,
			WritableStreamDefaultWriter: false,
		},
		parserOptions: { ecmaFeatures: { globalReturn: true } },
	},
	rules: {
		'callback-return': 'off',
		'global-require': 'error',
		'handle-callback-err': 'off',
		'no-buffer-constructor': 'error',
		'no-mixed-requires': ['off', false],
		'no-new-require': 'error',
		'no-path-concat': 'error',
		'no-process-env': 'off',
		'no-process-exit': 'off',
		'no-restricted-modules': 'off',
		'no-sync': 'off',
	},
};
